version: '3.8'

services:
  frontend:
    build:
      context: ./client  # Ścieżka do katalogu frontendu
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Mapowanie portu 3000 kontenera na port 3000 hosta
    depends_on:
      - backend
    env_file:
      - ./client/.env

  backend:
    build:
      context: ./server  # Ścieżka do katalogu backendu
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
