version: '3.8'

services:
  frontend:
    build:
      context: ./client  # Ścieżka do katalogu frontendu
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

  backend:
    build:
      context: ./server  # Ścieżka do katalogu backendu
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"